permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Hu Zhanchi 
  email: zhanchihu@gmail.com 
  link: http://armstronghu.github.io
  weibo: http://weibo.com/orangeissweet
  github: http://github.com/armstronghu
  douban: http://www.douban.com/people/64696367/ 
  linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: 胡展翅的博客 
description: My personal blog
url: http://armstronghu.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/avatar.jpg
favicon: /public/img/avatar.jpg

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: armstronghu 

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
